/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Grapxly (https://sketchfab.com/grapxly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-chair-8352824055b04ca29137ad463525d577
Title: Gaming Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { a } from '@react-spring/three'
import chairScene from './assets/GamingChairNoBin/compressed_chair.glb'

const CompressedChair = (props) => {
  const chairRef = useRef()

  useFrame(()=>{
    if(chairRef.current){
        chairRef.current.rotation.y += 0.01
    }
  })

  const { nodes, materials } = useGLTF(chairScene)
  return (
    <a.group ref={chairRef} {...props} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0.526, 0.045]}
        scale={[0.154, 0.202, 0.255]}
      />
    </a.group>
  )
}

export default CompressedChair